"""my first migration

Revision ID: 5174b3b2c5af
Revises: c086fa119615
Create Date: 2021-03-17 19:52:25.946457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5174b3b2c5af'
down_revision = 'c086fa119615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('hash_key', sa.String(length=10), nullable=True))
    op.add_column('chat', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_chat_hash_key'), 'chat', ['hash_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_hash_key'), table_name='chat')
    op.drop_column('chat', 'name')
    op.drop_column('chat', 'hash_key')
    # ### end Alembic commands ###
